In [ ]:
import numpy as np

### Numpy

Create a new array of 2*2 integers, without initializing entries.

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

Let X = np.array([1,2,3], [4,5,6], np.int32). Create a new array with the same shape and type as X.

In [ ]:
X = np.array([[1,2,3], [4,5,6], np.int32])
np.full_like(X, X.shape)

<ipython-input-3-39f3a83ea2f8>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X = np.array([[1,2,3], [4,5,6], np.int32])


array([3, 3, 3], dtype=object)

Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a new array of 3*2 float numbers, filled with ones.

In [ ]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Create a new array of 3*2 float numbers, filled with zeros.

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Create a new array of 2*5 uints, filled with 6.

In [ ]:
np.ones((2,5), dtype="uint64") * 6

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint64)

## From existing data

Create an array of [1, 2, 3].

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [ ]:
X = np.array([[1, 2], [3, 4]])
np.matrix(X)

matrix([[1, 2],
        [3, 4]])

Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [ ]:
x = np.array([1, 2, 3])
y = np.copy(x)
print(id(x), x)
print(id(y), y)

140554756107888 [1 2 3]
140554756129104 [1 2 3]


## Numerical ranges


Create an array of 2, 4, 6, 8, ..., 100.

In [ ]:
np.arange(2, 101, 2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [ ]:
np.linspace(3, 10, 50)

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

Let X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]]). Get the diagonal of X, that is, [0, 5, 10].

In [ ]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
np.diag(X)

array([ 0,  5, 10])

Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

In [ ]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Q1. Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.

In [ ]:
x = np.ones([10, 10, 3])
x.reshape(2, 150)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.,

Q2. Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(np.concatenate(np.column_stack(x)))

[1 4 2 5 3 6]


Q3. Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element.

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x[1, 1]

5

Q1. Return the minimum value of x along the second axis.

In [ ]:
x = np.array([[0, 1], [2, 3]])
ans = np.min(x, axis=1)
print("x =\n", x)
print("ans =\n", ans)

x =
 [[0 1]
 [2 3]]
ans =
 [0 2]


Q2. Return the maximum value of x along the second axis. Reduce the second axis to the dimension with size one.

In [ ]:
ans = np.max(x, axis=1)
ans = np.array([ans])
print("x =\n", x)
print("ans =\n", ans.T)

x =
 [[0 1]
 [2 3]]
ans =
 [[1]
 [3]]
